image:
  repository: ghcr.io/actions/gha-runner-scale-set-controller
  pullPolicy: IfNotPresent
  tag: 0.14.2@sha256:1b4c7f62e971ab259a4b8798e48e2adaad4af747f45990f474ea5feefa03531d

serviceAccount:
  create: true
  name: arc-controller

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

flags:
  logLevel: info
  logFormat: text
  watchSingleNamespace: arc-runners
  runnerMaxConcurrentReconciles: 2
  updateStrategy: eventual
