apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-applications
  namespace: argocd
rules:
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zabbix-applications
  namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zabbix-applications
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: zabbix
