apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-coredns-service
  namespace: default
rules:
  - apiGroups: [""]
    resources: [services]
    resourceNames: [kubernetes]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zabbix-coredns-service
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zabbix-coredns-service
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: zabbix
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zabbix-coredns-service
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: [services]
    resourceNames: [kube-dns]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zabbix-coredns-service
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zabbix-coredns-service
subjects:
  - kind: ServiceAccount
    name: collector
    namespace: zabbix
