apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - deployment.yaml
  - collector.yaml
  - network-policy.yaml
  - oidc-client.yaml
  - oauth2-proxy.yaml
  - ingress.yaml
configMapGenerator:
  - name: collector
    namespace: zabbix
    files:
      - assets/collector.py
      - assets/functional.py
      - assets/service_portal.py
      - assets/service_portal.json
      - assets/mail_activity.py
      - assets/policy.json
generatorOptions:
  disableNameSuffixHash: true
