apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-secrets
  namespace: argocd
  annotations:
    # Ensure secrets are created before authentik app syncs
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/authentik/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

