apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forecastle
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: forecastle
      targetRevision: 1.0.145
      helm:
        valueFiles:
          - $values/config/forecastle/values.yaml
    - repoURL: https://github.com/alpar-t/homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: forecastle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

