# k3s Upgrade Plan - requires system-upgrade-controller to be synced first
#
# To upgrade k3s: update the version in
# config/system-upgrade-controller/plan/k3s-upgrade-plan.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-upgrade-plan
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-14"
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/system-upgrade-controller/plan
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
