apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/longhorn/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

