apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  sources:
    # MetalLB Helm chart
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.9
      helm:
        values: |
          speaker:
            frr:
              enabled: false
    # Configuration manifests (IPAddressPool, L2Advertisement)
    - repoURL: https://github.com/alpar-t/homelab
      targetRevision: main
      path: config/metallb/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
