apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multus
  namespace: argocd
  annotations:
    # Deploy before Longhorn to ensure NetworkAttachmentDefinition CRD exists
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://rke2-charts.rancher.io
    chart: rke2-multus
    targetRevision: v4.2.202
    helm:
      values: |
        config:
          fullnameOverride: multus
          cni_conf:
            confDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
            binDir: /var/lib/rancher/k3s/data/cni/
            kubeconfig: /var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
            multusAutoconfigDir: /var/lib/rancher/k3s/agent/etc/cni/net.d
        manifests:
          dhcpDaemonSet: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
