apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-frigate
  namespace: argocd
  annotations:
    # Run after pocket-id is deployed
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/oauth2-proxy-frigate/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: frigate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

