# OAuth2 Proxy for Chatwoot authentication via Pocket ID

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-chatwoot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/oauth2-proxy-chatwoot/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: chatwoot
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

