apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-onlyoffice
  namespace: argocd
  annotations:
    # Run after pocket-id and onlyoffice are deployed
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/oauth2-proxy-onlyoffice/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

