apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onlyoffice
  namespace: argocd
spec:
  project: default
  sources:
    # OnlyOffice PostgreSQL (CloudNativePG)
    - repoURL: https://github.com/alpar-t/homelab
      targetRevision: main
      path: config/onlyoffice/manifests
    # OnlyOffice Helm Chart
    - repoURL: https://download.onlyoffice.com/charts/stable
      chart: docs
      targetRevision: "*"
      helm:
        releaseName: onlyoffice
        valueFiles:
          - $values/config/onlyoffice/helm/values.yaml
    # Values from git repo (referenced by $values)
    - repoURL: https://github.com/alpar-t/homelab
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

