apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: default
  source:
    # Pre-rendered manifests from Helm chart + Pocket ID modifications
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/owncloud/rendered
  destination:
    server: https://kubernetes.default.svc
    namespace: owncloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
