apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roundcube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/alpar-t/homelab
    targetRevision: main
    path: config/roundcube/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: roundcube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

