apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newjoy-website-build
  namespace: arc-runners
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 30Gi
